# Generated by Django 5.0.1 on 2026-02-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorol',
            name='unidad_organica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_roles', to='organizacion.unidadorganica'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together={('rol', 'permiso')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('usuario', 'rol', 'unidad_organica')},
        ),
    ]
