# Generated by Django 5.0.1 on 2026-02-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_cerrado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Año Fiscal',
                'verbose_name_plural': 'Años Fiscales',
                'db_table': 'anio_fiscal',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='ClasificadorGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('tipo_transaccion', models.CharField(blank=True, default='', max_length=100)),
                ('generica', models.CharField(blank=True, default='', max_length=100)),
                ('subgenerica', models.CharField(blank=True, default='', max_length=100)),
                ('especifica', models.CharField(blank=True, default='', max_length=100)),
                ('nombre_tipo_transaccion', models.CharField(blank=True, default='', max_length=100)),
                ('nombre_generica', models.CharField(blank=True, default='', max_length=200)),
                ('nombre_subgenerica', models.CharField(blank=True, default='', max_length=200)),
                ('nombre_subgenerica_det', models.CharField(blank=True, default='', max_length=200)),
                ('nombre_especifica', models.CharField(blank=True, default='', max_length=200)),
                ('nombre_especifica_det', models.CharField(blank=True, default='', max_length=300)),
                ('descripcion_detallada', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clasificador de Gasto',
                'verbose_name_plural': 'Clasificadores de Gasto',
                'db_table': 'clasificador_gasto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FuenteFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_corto', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fuente de Financiamiento',
                'verbose_name_plural': 'Fuentes de Financiamiento',
                'db_table': 'fuente_financiamiento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_corto', models.CharField(blank=True, default='', max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='catalogos.fuentefinanciamiento')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'db_table': 'rubro',
                'ordering': ['codigo'],
            },
        ),
    ]
