# Generated by Django 5.0.1 on 2026-02-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificadorgasto',
            name='especifica_det',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clasificadorgasto',
            name='subgenerica_det',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
