# Generated by Django 5.0.1 on 2026-02-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadOrganica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_corto', models.CharField(blank=True, default='', max_length=50)),
                ('nivel', models.IntegerField(choices=[(1, 'Órgano'), (2, 'Unidad Orgánica'), (3, 'Sub Unidad Orgánica')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='organizacion.unidadorganica')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad Orgánica',
                'verbose_name_plural': 'Unidades Orgánicas',
                'db_table': 'unidad_organica',
                'ordering': ['codigo'],
            },
        ),
    ]
