# Generated by Django 5.0.1 on 2026-02-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='uploads/excel/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('hash_archivo', models.CharField(max_length=64)),
                ('tamanio', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error'), ('PARCIAL', 'Completado parcialmente')], default='PENDIENTE', max_length=20)),
                ('total_filas', models.IntegerField(default=0)),
                ('filas_procesadas', models.IntegerField(default=0)),
                ('filas_con_error', models.IntegerField(default=0)),
                ('filas_creadas', models.IntegerField(default=0)),
                ('filas_actualizadas', models.IntegerField(default=0)),
                ('filas_sin_cambios', models.IntegerField(default=0)),
                ('log_errores', models.JSONField(blank=True, default=list)),
                ('estadisticas_detalle', models.JSONField(blank=True, default=dict)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('anio_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='catalogos.aniofiscal')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación de Archivo',
                'verbose_name_plural': 'Importaciones de Archivos',
                'db_table': 'importacion_archivo',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
