# Generated by Django 5.0.1 on 2026-02-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('SUBEJECUCION', 'Sub ejecución'), ('SOBRECERTIFICACION', 'Sobre certificación'), ('META_ATRASADA', 'Meta atrasada'), ('MODIFICACION', 'Modificación presupuestal'), ('VENCIMIENTO', 'Vencimiento')], max_length=30)),
                ('nivel_severidad', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('datos_contexto', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('LEIDA', 'Leída'), ('RESUELTA', 'Resuelta')], default='ACTIVA', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('anio_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='catalogos.aniofiscal')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerta',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='alertas.alerta')),
            ],
            options={
                'verbose_name': 'Notificación de Usuario',
                'verbose_name_plural': 'Notificaciones de Usuarios',
                'db_table': 'notificacion_usuario',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
