# Generated by Django 5.0.1 on 2026-02-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('importacion', '0001_initial'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=500)),
                ('finalidad', models.TextField(blank=True, default='')),
                ('tipo_meta', models.CharField(choices=[('ACTIVIDAD', 'Actividad'), ('PROYECTO', 'Proyecto')], default='ACTIVIDAD', max_length=20)),
                ('cantidad_meta_anual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sec_func', models.IntegerField(blank=True, null=True)),
                ('codigo_programa_pptal', models.CharField(blank=True, default='', max_length=20)),
                ('codigo_producto_proyecto', models.CharField(blank=True, default='', max_length=20)),
                ('codigo_actividad', models.CharField(blank=True, default='', max_length=20)),
                ('codigo_funcion', models.CharField(blank=True, default='', max_length=10)),
                ('codigo_division_fn', models.CharField(blank=True, default='', max_length=10)),
                ('codigo_grupo_fn', models.CharField(blank=True, default='', max_length=10)),
                ('codigo_finalidad', models.CharField(blank=True, default='', max_length=20)),
                ('nombre_programa_pptal', models.CharField(blank=True, default='', max_length=300)),
                ('nombre_producto_proyecto', models.CharField(blank=True, default='', max_length=500)),
                ('nombre_actividad', models.CharField(blank=True, default='', max_length=500)),
                ('tipo_producto_proyecto', models.CharField(blank=True, default='', max_length=50)),
                ('tipo_actividad', models.CharField(blank=True, default='', max_length=50)),
                ('codigo_unidad_medida', models.CharField(blank=True, default='', max_length=10)),
                ('nombre_unidad_medida', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('anio_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='catalogos.aniofiscal')),
                ('unidad_organica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas', to='organizacion.unidadorganica')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'meta',
                'ordering': ['codigo'],
                'unique_together': {('anio_fiscal', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='EjecucionPresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_categoria_gasto', models.CharField(blank=True, default='', max_length=10)),
                ('nombre_categoria_gasto', models.CharField(blank=True, default='', max_length=100)),
                ('restringido', models.BooleanField(default=False)),
                ('pia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('modificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pim', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('certificado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('compromiso_anual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('anio_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='catalogos.aniofiscal')),
                ('archivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones', to='importacion.importacionarchivo')),
                ('clasificador_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='catalogos.clasificadorgasto')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones_importadas', to=settings.AUTH_USER_MODEL)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='catalogos.rubro')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='presupuesto.meta')),
            ],
            options={
                'verbose_name': 'Ejecución Presupuestal',
                'verbose_name_plural': 'Ejecuciones Presupuestales',
                'db_table': 'ejecucion_presupuestal',
            },
        ),
        migrations.CreateModel(
            name='AvanceFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_meta_semestral', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avance_fisico_anual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avance_fisico_semestral', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_registrados', to=settings.AUTH_USER_MODEL)),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avance_fisico', to='presupuesto.meta')),
            ],
            options={
                'verbose_name': 'Avance Físico',
                'verbose_name_plural': 'Avances Físicos',
                'db_table': 'avance_fisico',
            },
        ),
        migrations.CreateModel(
            name='ModificacionPresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito Suplementario'), ('TRANSFERENCIA', 'Transferencia de Partidas'), ('HABILITACION', 'Habilitación'), ('ANULACION', 'Anulación')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('documento_referencia', models.CharField(blank=True, default='', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_modificacion', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones_detalle', to='presupuesto.ejecucionpresupuestal')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modificación Presupuestal',
                'verbose_name_plural': 'Modificaciones Presupuestales',
                'db_table': 'modificacion_presupuestal',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('compromiso', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('devengado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('girado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pagado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensuales', to='presupuesto.ejecucionpresupuestal')),
            ],
            options={
                'verbose_name': 'Ejecución Mensual',
                'verbose_name_plural': 'Ejecuciones Mensuales',
                'db_table': 'ejecucion_mensual',
                'ordering': ['ejecucion', 'mes'],
                'indexes': [models.Index(fields=['ejecucion', 'mes'], name='ejecucion_m_ejecuci_8407b1_idx')],
                'unique_together': {('ejecucion', 'mes')},
            },
        ),
        migrations.AddIndex(
            model_name='ejecucionpresupuestal',
            index=models.Index(fields=['anio_fiscal', 'meta'], name='ejecucion_p_anio_fi_078386_idx'),
        ),
        migrations.AddIndex(
            model_name='ejecucionpresupuestal',
            index=models.Index(fields=['anio_fiscal', 'rubro'], name='ejecucion_p_anio_fi_54b4ab_idx'),
        ),
    ]
