# Generated by Django 5.0.1 on 2026-03-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='tipo_actividad',
            field=models.CharField(blank=True, choices=[('ACTIVIDAD', 'Actividad'), ('OBRA', 'Obra'), ('ACCION_INVERSION', 'Acción de Inversión')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='meta',
            name='tipo_meta',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('PROYECTO', 'Proyecto')], default='PRODUCTO', max_length=20),
        ),
    ]
