# Generated by Django 5.0.1 on 2026-03-03 15:33

from django.db import migrations


def migrar_actividad_a_producto(apps, schema_editor):
    """Convierte registros con tipo_meta='ACTIVIDAD' a 'PRODUCTO'."""
    Meta = apps.get_model('presupuesto', 'Meta')
    updated = Meta.objects.filter(tipo_meta='ACTIVIDAD').update(tipo_meta='PRODUCTO')
    if updated:
        print(f'\n  Migrados {updated} registros: tipo_meta ACTIVIDAD -> PRODUCTO')


def revertir_producto_a_actividad(apps, schema_editor):
    """Revierte: convierte tipo_meta='PRODUCTO' de vuelta a 'ACTIVIDAD'."""
    Meta = apps.get_model('presupuesto', 'Meta')
    Meta.objects.filter(tipo_meta='PRODUCTO').update(tipo_meta='ACTIVIDAD')


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_corregir_tipo_meta_producto_proyecto'),
    ]

    operations = [
        migrations.RunPython(
            migrar_actividad_a_producto,
            revertir_producto_a_actividad,
        ),
    ]
